# Dependency Properties
zip4j.version=2.11.5
minecraft.version=26.2.build.+
kyori.adventure.version=4.21.0
protocol.sidebar.version=6.2.7-SNAPSHOT-pr79
worldedit.version=7.4.5
litecommands.version=3.5.0
okaeri.configs.version=5.0.5
apache.commons.io.version=2.17.0
mrstudios.commons.version=1.1.1
jetbrains.annotations.version=26.0.2

# Gradle Properties
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
